#!/usr/bin/env bash
# commands lines to  Install Nginx
sudo apt-get update -y
sudo apt install nginx -y
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#test nginx conf
sudo nginx -t

sudo service nginx reload
