#!/usr/bin/env bash
# set the 404 page not found 

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me hhtps;\/\/github.com\/zachafs permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/site-enabled/default

# creating rj script 0404 error page

echo" Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t"

sudo sed -i "s/listen 80 default_server;/$string_for_replacemnt/" /etc/nginx/site-enables/default

#Now lets restart ngnx after the implimentation
 
sudo service nginx restart
